using System;
using System.Collections.Generic;
using UnityEngine;

namespace PotatoSerializer {
	public interface ISerializer {
		bool IsReading { get; }
		bool IsWriting { get; }

		void Serialize(string name, ref bool value);
		void Serialize(string name, ref bool[] value);
		void Serialize(string name, ref byte value);
		void Serialize(string name, ref byte[] value);
		void Serialize(string name, ref Color value);
		void Serialize(string name, ref Color[] value);
		void Serialize(string name, ref double value);
		void Serialize(string name, ref double[] value);
		void Serialize(string name, ref float value);
		void Serialize(string name, ref float[] value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, bool[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, bool> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, byte[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, byte> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, Color[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, Color> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, double[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, double> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, float[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, float> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<bool>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<byte>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<Color>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<double>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<float>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<int>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ISerialObject>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ISerialProxy<bool>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ISerialProxy<byte>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ISerialProxy<double>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ISerialProxy<float>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ISerialProxy<int>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ISerialProxy<long>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ISerialProxy<sbyte>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ISerialProxy<short>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ISerialProxy<string>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ISerialProxy<uint>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ISerialProxy<ulong>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ISerialProxy<ushort>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<long>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<Quaternion>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<sbyte>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<short>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<string>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<uint>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ulong>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<ushort>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<Vector2>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<Vector2Int>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<Vector3>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, IList<Vector3Int>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, int[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, int> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialObject[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialObject> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<bool>[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<bool>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<byte>[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<byte>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<double>[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<double>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<float>[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<float>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<int>[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<int>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<long>[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<long>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<sbyte>[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<sbyte>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<short>[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<short>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<string>[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<string>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<uint>[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<uint>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<ulong>[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<ulong>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<ushort>[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISerialProxy<ushort>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<bool>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<byte>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<Color>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<double>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<float>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<int>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ISerialObject>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ISerialProxy<bool>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ISerialProxy<byte>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ISerialProxy<double>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ISerialProxy<float>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ISerialProxy<int>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ISerialProxy<long>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ISerialProxy<sbyte>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ISerialProxy<short>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ISerialProxy<string>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ISerialProxy<uint>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ISerialProxy<ulong>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ISerialProxy<ushort>>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<long>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<Quaternion>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<sbyte>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<short>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<string>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<uint>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ulong>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<ushort>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<Vector2>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<Vector2Int>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<Vector3>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ISet<Vector3Int>> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, long[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, long> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, Quaternion[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, Quaternion> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, sbyte[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, sbyte> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, short[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, short> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, string[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, string> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, uint[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, uint> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ulong[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ulong> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ushort[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, ushort> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, Vector2[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, Vector2> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, Vector2Int[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, Vector2Int> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, Vector3[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, Vector3> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, Vector3Int[]> value);
		void Serialize(string name, ref IDictionary<ISerialProxy<string>, Vector3Int> value);
		void Serialize(string name, ref IDictionary<string, bool[]> value);
		void Serialize(string name, ref IDictionary<string, bool> value);
		void Serialize(string name, ref IDictionary<string, byte[]> value);
		void Serialize(string name, ref IDictionary<string, byte> value);
		void Serialize(string name, ref IDictionary<string, Color[]> value);
		void Serialize(string name, ref IDictionary<string, Color> value);
		void Serialize(string name, ref IDictionary<string, double[]> value);
		void Serialize(string name, ref IDictionary<string, double> value);
		void Serialize(string name, ref IDictionary<string, float[]> value);
		void Serialize(string name, ref IDictionary<string, float> value);
		void Serialize(string name, ref IDictionary<string, IList<bool>> value);
		void Serialize(string name, ref IDictionary<string, IList<byte>> value);
		void Serialize(string name, ref IDictionary<string, IList<Color>> value);
		void Serialize(string name, ref IDictionary<string, IList<double>> value);
		void Serialize(string name, ref IDictionary<string, IList<float>> value);
		void Serialize(string name, ref IDictionary<string, IList<int>> value);
		void Serialize(string name, ref IDictionary<string, IList<ISerialObject>> value);
		void Serialize(string name, ref IDictionary<string, IList<ISerialProxy<bool>>> value);
		void Serialize(string name, ref IDictionary<string, IList<ISerialProxy<byte>>> value);
		void Serialize(string name, ref IDictionary<string, IList<ISerialProxy<double>>> value);
		void Serialize(string name, ref IDictionary<string, IList<ISerialProxy<float>>> value);
		void Serialize(string name, ref IDictionary<string, IList<ISerialProxy<int>>> value);
		void Serialize(string name, ref IDictionary<string, IList<ISerialProxy<long>>> value);
		void Serialize(string name, ref IDictionary<string, IList<ISerialProxy<sbyte>>> value);
		void Serialize(string name, ref IDictionary<string, IList<ISerialProxy<short>>> value);
		void Serialize(string name, ref IDictionary<string, IList<ISerialProxy<string>>> value);
		void Serialize(string name, ref IDictionary<string, IList<ISerialProxy<uint>>> value);
		void Serialize(string name, ref IDictionary<string, IList<ISerialProxy<ulong>>> value);
		void Serialize(string name, ref IDictionary<string, IList<ISerialProxy<ushort>>> value);
		void Serialize(string name, ref IDictionary<string, IList<long>> value);
		void Serialize(string name, ref IDictionary<string, IList<Quaternion>> value);
		void Serialize(string name, ref IDictionary<string, IList<sbyte>> value);
		void Serialize(string name, ref IDictionary<string, IList<short>> value);
		void Serialize(string name, ref IDictionary<string, IList<string>> value);
		void Serialize(string name, ref IDictionary<string, IList<uint>> value);
		void Serialize(string name, ref IDictionary<string, IList<ulong>> value);
		void Serialize(string name, ref IDictionary<string, IList<ushort>> value);
		void Serialize(string name, ref IDictionary<string, IList<Vector2>> value);
		void Serialize(string name, ref IDictionary<string, IList<Vector2Int>> value);
		void Serialize(string name, ref IDictionary<string, IList<Vector3>> value);
		void Serialize(string name, ref IDictionary<string, IList<Vector3Int>> value);
		void Serialize(string name, ref IDictionary<string, int[]> value);
		void Serialize(string name, ref IDictionary<string, int> value);
		void Serialize(string name, ref IDictionary<string, ISerialObject[]> value);
		void Serialize(string name, ref IDictionary<string, ISerialObject> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<bool>[]> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<bool>> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<byte>[]> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<byte>> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<double>[]> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<double>> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<float>[]> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<float>> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<int>[]> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<int>> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<long>[]> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<long>> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<sbyte>[]> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<sbyte>> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<short>[]> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<short>> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<string>[]> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<string>> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<uint>[]> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<uint>> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<ulong>[]> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<ulong>> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<ushort>[]> value);
		void Serialize(string name, ref IDictionary<string, ISerialProxy<ushort>> value);
		void Serialize(string name, ref IDictionary<string, ISet<bool>> value);
		void Serialize(string name, ref IDictionary<string, ISet<byte>> value);
		void Serialize(string name, ref IDictionary<string, ISet<Color>> value);
		void Serialize(string name, ref IDictionary<string, ISet<double>> value);
		void Serialize(string name, ref IDictionary<string, ISet<float>> value);
		void Serialize(string name, ref IDictionary<string, ISet<int>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ISerialObject>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ISerialProxy<bool>>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ISerialProxy<byte>>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ISerialProxy<double>>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ISerialProxy<float>>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ISerialProxy<int>>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ISerialProxy<long>>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ISerialProxy<sbyte>>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ISerialProxy<short>>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ISerialProxy<string>>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ISerialProxy<uint>>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ISerialProxy<ulong>>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ISerialProxy<ushort>>> value);
		void Serialize(string name, ref IDictionary<string, ISet<long>> value);
		void Serialize(string name, ref IDictionary<string, ISet<Quaternion>> value);
		void Serialize(string name, ref IDictionary<string, ISet<sbyte>> value);
		void Serialize(string name, ref IDictionary<string, ISet<short>> value);
		void Serialize(string name, ref IDictionary<string, ISet<string>> value);
		void Serialize(string name, ref IDictionary<string, ISet<uint>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ulong>> value);
		void Serialize(string name, ref IDictionary<string, ISet<ushort>> value);
		void Serialize(string name, ref IDictionary<string, ISet<Vector2>> value);
		void Serialize(string name, ref IDictionary<string, ISet<Vector2Int>> value);
		void Serialize(string name, ref IDictionary<string, ISet<Vector3>> value);
		void Serialize(string name, ref IDictionary<string, ISet<Vector3Int>> value);
		void Serialize(string name, ref IDictionary<string, long[]> value);
		void Serialize(string name, ref IDictionary<string, long> value);
		void Serialize(string name, ref IDictionary<string, Quaternion[]> value);
		void Serialize(string name, ref IDictionary<string, Quaternion> value);
		void Serialize(string name, ref IDictionary<string, sbyte[]> value);
		void Serialize(string name, ref IDictionary<string, sbyte> value);
		void Serialize(string name, ref IDictionary<string, short[]> value);
		void Serialize(string name, ref IDictionary<string, short> value);
		void Serialize(string name, ref IDictionary<string, string[]> value);
		void Serialize(string name, ref IDictionary<string, string> value);
		void Serialize(string name, ref IDictionary<string, uint[]> value);
		void Serialize(string name, ref IDictionary<string, uint> value);
		void Serialize(string name, ref IDictionary<string, ulong[]> value);
		void Serialize(string name, ref IDictionary<string, ulong> value);
		void Serialize(string name, ref IDictionary<string, ushort[]> value);
		void Serialize(string name, ref IDictionary<string, ushort> value);
		void Serialize(string name, ref IDictionary<string, Vector2[]> value);
		void Serialize(string name, ref IDictionary<string, Vector2> value);
		void Serialize(string name, ref IDictionary<string, Vector2Int[]> value);
		void Serialize(string name, ref IDictionary<string, Vector2Int> value);
		void Serialize(string name, ref IDictionary<string, Vector3[]> value);
		void Serialize(string name, ref IDictionary<string, Vector3> value);
		void Serialize(string name, ref IDictionary<string, Vector3Int[]> value);
		void Serialize(string name, ref IDictionary<string, Vector3Int> value);
		void Serialize(string name, ref IList<bool> value);
		void Serialize(string name, ref IList<byte> value);
		void Serialize(string name, ref IList<Color> value);
		void Serialize(string name, ref IList<double> value);
		void Serialize(string name, ref IList<float> value);
		void Serialize(string name, ref IList<int> value);
		void Serialize(string name, ref IList<ISerialObject> value);
		void Serialize(string name, ref IList<ISerialProxy<bool>> value);
		void Serialize(string name, ref IList<ISerialProxy<byte>> value);
		void Serialize(string name, ref IList<ISerialProxy<double>> value);
		void Serialize(string name, ref IList<ISerialProxy<float>> value);
		void Serialize(string name, ref IList<ISerialProxy<int>> value);
		void Serialize(string name, ref IList<ISerialProxy<long>> value);
		void Serialize(string name, ref IList<ISerialProxy<sbyte>> value);
		void Serialize(string name, ref IList<ISerialProxy<short>> value);
		void Serialize(string name, ref IList<ISerialProxy<string>> value);
		void Serialize(string name, ref IList<ISerialProxy<uint>> value);
		void Serialize(string name, ref IList<ISerialProxy<ulong>> value);
		void Serialize(string name, ref IList<ISerialProxy<ushort>> value);
		void Serialize(string name, ref IList<long> value);
		void Serialize(string name, ref IList<Quaternion> value);
		void Serialize(string name, ref IList<sbyte> value);
		void Serialize(string name, ref IList<short> value);
		void Serialize(string name, ref IList<string> value);
		void Serialize(string name, ref IList<uint> value);
		void Serialize(string name, ref IList<ulong> value);
		void Serialize(string name, ref IList<ushort> value);
		void Serialize(string name, ref IList<Vector2> value);
		void Serialize(string name, ref IList<Vector2Int> value);
		void Serialize(string name, ref IList<Vector3> value);
		void Serialize(string name, ref IList<Vector3Int> value);
		void Serialize(string name, ref int value);
		void Serialize(string name, ref int[] value);
		void Serialize(string name, ref ISerialObject value);
		void Serialize(string name, ref ISerialObject[] value);
		void Serialize(string name, ref ISerialProxy<bool> value);
		void Serialize(string name, ref ISerialProxy<bool>[] value);
		void Serialize(string name, ref ISerialProxy<byte> value);
		void Serialize(string name, ref ISerialProxy<byte>[] value);
		void Serialize(string name, ref ISerialProxy<double> value);
		void Serialize(string name, ref ISerialProxy<double>[] value);
		void Serialize(string name, ref ISerialProxy<float> value);
		void Serialize(string name, ref ISerialProxy<float>[] value);
		void Serialize(string name, ref ISerialProxy<int> value);
		void Serialize(string name, ref ISerialProxy<int>[] value);
		void Serialize(string name, ref ISerialProxy<long> value);
		void Serialize(string name, ref ISerialProxy<long>[] value);
		void Serialize(string name, ref ISerialProxy<sbyte> value);
		void Serialize(string name, ref ISerialProxy<sbyte>[] value);
		void Serialize(string name, ref ISerialProxy<short> value);
		void Serialize(string name, ref ISerialProxy<short>[] value);
		void Serialize(string name, ref ISerialProxy<string> value);
		void Serialize(string name, ref ISerialProxy<string>[] value);
		void Serialize(string name, ref ISerialProxy<uint> value);
		void Serialize(string name, ref ISerialProxy<uint>[] value);
		void Serialize(string name, ref ISerialProxy<ulong> value);
		void Serialize(string name, ref ISerialProxy<ulong>[] value);
		void Serialize(string name, ref ISerialProxy<ushort> value);
		void Serialize(string name, ref ISerialProxy<ushort>[] value);
		void Serialize(string name, ref ISet<bool> value);
		void Serialize(string name, ref ISet<byte> value);
		void Serialize(string name, ref ISet<Color> value);
		void Serialize(string name, ref ISet<double> value);
		void Serialize(string name, ref ISet<float> value);
		void Serialize(string name, ref ISet<int> value);
		void Serialize(string name, ref ISet<ISerialObject> value);
		void Serialize(string name, ref ISet<ISerialProxy<bool>> value);
		void Serialize(string name, ref ISet<ISerialProxy<byte>> value);
		void Serialize(string name, ref ISet<ISerialProxy<double>> value);
		void Serialize(string name, ref ISet<ISerialProxy<float>> value);
		void Serialize(string name, ref ISet<ISerialProxy<int>> value);
		void Serialize(string name, ref ISet<ISerialProxy<long>> value);
		void Serialize(string name, ref ISet<ISerialProxy<sbyte>> value);
		void Serialize(string name, ref ISet<ISerialProxy<short>> value);
		void Serialize(string name, ref ISet<ISerialProxy<string>> value);
		void Serialize(string name, ref ISet<ISerialProxy<uint>> value);
		void Serialize(string name, ref ISet<ISerialProxy<ulong>> value);
		void Serialize(string name, ref ISet<ISerialProxy<ushort>> value);
		void Serialize(string name, ref ISet<long> value);
		void Serialize(string name, ref ISet<Quaternion> value);
		void Serialize(string name, ref ISet<sbyte> value);
		void Serialize(string name, ref ISet<short> value);
		void Serialize(string name, ref ISet<string> value);
		void Serialize(string name, ref ISet<uint> value);
		void Serialize(string name, ref ISet<ulong> value);
		void Serialize(string name, ref ISet<ushort> value);
		void Serialize(string name, ref ISet<Vector2> value);
		void Serialize(string name, ref ISet<Vector2Int> value);
		void Serialize(string name, ref ISet<Vector3> value);
		void Serialize(string name, ref ISet<Vector3Int> value);
		void Serialize(string name, ref long value);
		void Serialize(string name, ref long[] value);
		void Serialize(string name, ref Quaternion value);
		void Serialize(string name, ref Quaternion[] value);
		void Serialize(string name, ref sbyte value);
		void Serialize(string name, ref sbyte[] value);
		void Serialize(string name, ref short value);
		void Serialize(string name, ref short[] value);
		void Serialize(string name, ref string value);
		void Serialize(string name, ref string[] value);
		void Serialize(string name, ref uint value);
		void Serialize(string name, ref uint[] value);
		void Serialize(string name, ref ulong value);
		void Serialize(string name, ref ulong[] value);
		void Serialize(string name, ref ushort value);
		void Serialize(string name, ref ushort[] value);
		void Serialize(string name, ref Vector2 value);
		void Serialize(string name, ref Vector2[] value);
		void Serialize(string name, ref Vector2Int value);
		void Serialize(string name, ref Vector2Int[] value);
		void Serialize(string name, ref Vector3 value);
		void Serialize(string name, ref Vector3[] value);
		void Serialize(string name, ref Vector3Int value);
		void Serialize(string name, ref Vector3Int[] value);
		void Serialize<T>(string name, ref IDictionary<ISerialProxy<string>, IList<T>> value) where T : Enum;
		void Serialize<T>(string name, ref IDictionary<ISerialProxy<string>, ISet<T>> value) where T : Enum;
		void Serialize<T>(string name, ref IDictionary<ISerialProxy<string>, T[]> value) where T : Enum;
		void Serialize<T>(string name, ref IDictionary<ISerialProxy<string>, T> value) where T : Enum;
		void Serialize<T>(string name, ref IDictionary<string, IList<T>> value) where T : Enum;
		void Serialize<T>(string name, ref IDictionary<string, ISet<T>> value) where T : Enum;
		void Serialize<T>(string name, ref IDictionary<string, T[]> value) where T : Enum;
		void Serialize<T>(string name, ref IDictionary<string, T> value) where T : Enum;
		void Serialize<T>(string name, ref IList<T> value) where T : Enum;
		void Serialize<T>(string name, ref ISet<T> value) where T : Enum;
		void Serialize<T>(string name, ref T value) where T : Enum;
		void Serialize<T>(string name, ref T[] value) where T : Enum;
	}
}